// AUTO-GENERATED by scripts/build-custom-images.js — do not edit by hand.
// Holds the owner's own images (dropped into assets/custom/**). Empty is fine.

export const CUSTOM_DEITIES: Record<string, number> = {

};

export const CUSTOM_FOOD: Record<string, number> = {

};

export const CUSTOM_WALLPAPERS: Record<string, number> = {

};
