// Puja guides — what to gather, what to strictly avoid, and how to worship.
// Grounded in widely-followed tradition; regional practice may vary, and the
// UI says so. "avoid" lists only well-established prohibitions.

export interface PujaGuide {
  id: string;
  deity: string;
  deityHi: string;
  icon: string;
  color: string;
  day: string;               // traditional day of worship
  samagri: string[];         // what you need
  offerings: string[];       // favoured bhog/flowers
  strictlyAvoid: string[];   // established prohibitions
  steps: string[];           // simple vidhi
  mantra: string;            // core mantra (Devanagari)
  devotionalId?: string;     // link into the Devotional Library
  playQuery: string;         // for in-app video
}

export const PUJA_GUIDES: PujaGuide[] = [
  {
    id: 'ganesha',
    deity: 'Lord Ganesha',
    deityHi: 'श्री गणेश',
    icon: 'elephant',
    color: '#D94F00',
    day: 'Wednesday · Chaturthi',
    samagri: ['Ganesha murti or image', 'Chowki with red/yellow cloth', 'Diya with ghee', 'Agarbatti & dhoop', 'Roli, akshat (rice), kalava', 'Durva grass (21 blades)', 'Red flowers (hibiscus)', 'Modak or laddu for bhog', 'Paan, supari, fruit', 'Panchamrit (milk, curd, ghee, honey, sugar)'],
    offerings: ['Modak / besan laddu', 'Durva grass — dearest to Ganesha', 'Red hibiscus flowers', 'Banana and seasonal fruit'],
    strictlyAvoid: ['Tulsi leaves — never offered to Ganesha', 'Broken or dried durva', 'Ketaki (screw-pine) flowers', 'Onion & garlic in any bhog'],
    steps: ['Bathe and clean the puja space; face east or north-east', 'Place Ganesha on the chowki, light the diya and dhoop', 'Do achaman and sankalpa (state your intention)', 'Invoke Ganesha: "ॐ गं गणपतये नमः" and offer asana', 'Offer snan (panchamrit, then clean water), vastra, roli-tilak and akshat', 'Offer durva (in sets of 21) and red flowers', 'Offer modak/laddu bhog and fruit', 'Do the aarti "Jai Ganesh Deva" with the family', 'Seek forgiveness for errors (kshama prarthana) and distribute prasad'],
    mantra: 'वक्रतुण्ड महाकाय सूर्यकोटि समप्रभ।\nनिर्विघ्नं कुरु मे देव सर्वकार्येषु सर्वदा॥',
    devotionalId: 'jai-ganesh-deva',
    playQuery: 'Ganesh puja vidhi at home',
  },
  {
    id: 'shiva',
    deity: 'Lord Shiva',
    deityHi: 'भगवान शिव',
    icon: 'trident',
    color: '#37474F',
    day: 'Monday · Pradosh · Shivaratri',
    samagri: ['Shivling or Shiva image', 'Copper/brass lota for abhishek', 'Gangajal or clean water', 'Raw milk, curd, honey, ghee, sugar (panchamrit)', 'Bel patra (bilva leaves, 3-leaf sets)', 'White flowers (aak, dhatura optional per tradition)', 'Bhasma / vibhuti', 'Chandan (sandal paste)', 'Diya, dhoop', 'Fruit and simple mishri bhog'],
    offerings: ['Bel patra — most beloved, offered smooth side down', 'Water/milk abhishek in a steady thin stream', 'Chandan tilak (horizontal tripundra)', 'Dhatura and aak flowers (traditional)'],
    strictlyAvoid: ['Tulsi leaves — never on the Shivling', 'Ketaki (kewda) flowers — forbidden by the Shiva Purana', 'Haldi (turmeric) and kumkum on the Shivling', 'Shankh (conch) water for abhishek', 'Broken rice (khandit akshat)'],
    steps: ['Bathe; ideally worship during Brahma Muhurta or Pradosh time', 'Clean the Shivling and place it on a shallow tray facing north', 'Light diya and dhoop; do sankalpa', 'Abhishek: pour water, then panchamrit items one by one, then water again — chanting "ॐ नमः शिवाय"', 'Apply chandan tripundra; offer bel patra and white flowers', 'Offer fruit/mishri bhog', 'Recite Shiva mantra or Lingashtakam', 'Do the aarti "Om Jai Shiv Omkara"', 'Sit briefly in silence — Shiva puja ends in stillness'],
    mantra: 'ॐ त्र्यम्बकं यजामहे सुगन्धिं पुष्टिवर्धनम्।\nउर्वारुकमिव बन्धनान् मृत्योर्मुक्षीय मामृतात्॥',
    devotionalId: 'om-jai-shiv-omkara',
    playQuery: 'Shivling abhishek puja vidhi',
  },
  {
    id: 'lakshmi',
    deity: 'Goddess Lakshmi',
    deityHi: 'माँ लक्ष्मी',
    icon: 'flower-tulip',
    color: '#D32F2F',
    day: 'Friday · Diwali · Purnima',
    samagri: ['Lakshmi murti/image (with Ganesha for Diwali)', 'Red cloth for the chowki', 'Kamal gatta or lotus flowers', 'Kumkum, haldi, akshat', 'Ghee diya (traditionally 5 wicks on Friday/Diwali)', 'Kheer or white sweets for bhog', 'Coins / silver item to worship', 'Shree Yantra if available', 'Sandalwood, itra (fragrance)'],
    offerings: ['Lotus / red flowers', 'Kheer, white barfi, batasha', 'Fragrance and shringar items'],
    strictlyAvoid: ['Tulsi leaves — not offered to Lakshmi', 'White flowers of the aak/dhatura kind (they are for Shiva)', 'Keeping the space cluttered or dark — Lakshmi avoids untidiness', 'Onion & garlic in bhog'],
    steps: ['Clean the house/space thoroughly — this itself is Lakshmi-seva', 'Set the chowki with red cloth in the north-east; place the murti', 'Light the ghee diya and incense; do sankalpa', 'Invoke with "ॐ श्रीं महालक्ष्म्यै नमः"; offer asana and snan', 'Offer kumkum-haldi tilak, akshat, flowers and shringar', 'Worship coins/silver and your account book/tools if Diwali', 'Offer kheer/white sweet bhog', 'Do the aarti "Om Jai Lakshmi Mata"', 'Keep the diya burning a while; distribute prasad'],
    mantra: 'ॐ श्रीं ह्रीं श्रीं कमले कमलालये प्रसीद प्रसीद।\nॐ श्रीं ह्रीं श्रीं महालक्ष्म्यै नमः॥',
    devotionalId: 'om-jai-lakshmi',
    playQuery: 'Lakshmi puja vidhi at home',
  },
  {
    id: 'hanuman',
    deity: 'Lord Hanuman',
    deityHi: 'श्री हनुमान',
    icon: 'arm-flex',
    color: '#BF360C',
    day: 'Tuesday · Saturday',
    samagri: ['Hanuman image/murti', 'Sindoor and chameli (jasmine) oil', 'Red flowers, red cloth', 'Diya with til or chameli oil', 'Boondi laddu / gur-chana for bhog', 'Paan beeda', 'Hanuman Chalisa text (in this app!)'],
    offerings: ['Sindoor mixed with chameli oil (chola)', 'Boondi laddu, gur & roasted chana', 'Red flowers and paan'],
    strictlyAvoid: ['Any non-veg, onion, garlic in the home kitchen that day (traditional discipline)', 'Offering charnamrit made with... (regional variance — plain water/panchamrit is standard)', 'Torn or left-hand offered items', 'Alcohol/tobacco anywhere near the puja'],
    steps: ['Bathe; wear clean (preferably red/saffron) clothes', 'Light the oil diya before the image', 'Apply sindoor-chameli tilak to Hanuman ji and yourself', 'Offer red flowers and paan beeda', 'Recite Hanuman Chalisa (1, 7 or 11 paths)', 'Offer laddu/gur-chana bhog', 'Do the aarti "Aarti Kije Hanuman Lala Ki"', 'Read or listen to a Sundarkand passage if time allows'],
    mantra: 'मनोजवं मारुततुल्यवेगं जितेन्द्रियं बुद्धिमतां वरिष्ठम्।\nवातात्मजं वानरयूथमुख्यं श्रीरामदूतं शरणं प्रपद्ये॥',
    devotionalId: 'hanuman-chalisa',
    playQuery: 'Hanuman puja vidhi Tuesday',
  },
  {
    id: 'durga',
    deity: 'Maa Durga',
    deityHi: 'माँ दुर्गा',
    icon: 'shield-star',
    color: '#C62828',
    day: 'Tuesday · Friday · Navratri',
    samagri: ['Durga image/murti', 'Red chunri and red cloth', 'Kumkum, akshat, mehndi, choodi (shringar items)', 'Red hibiscus / rose flowers', 'Coconut, paan, supari', 'Ghee diya (akhand diya during Navratri)', 'Halwa-puri-chana for bhog (Ashtami style)', 'Kalash with water & mango leaves (Navratri)'],
    offerings: ['Red flowers and chunri', 'Shringar (solah shringar during Navratri)', 'Halwa, puri, kala chana'],
    strictlyAvoid: ['Durva grass — not offered to Devi', 'Onion, garlic and non-veg through the vrat/Navratri', 'Leather items in the puja space', 'Cutting hair/nails during Navratri (traditional discipline)'],
    steps: ['Clean the space; set the chowki with red cloth facing north-east', 'Place Maa Durga\'s image; Navratri: establish the kalash (ghatasthapana)', 'Light diya & dhoop; do sankalpa', 'Invoke with "ॐ दुं दुर्गायै नमः"; offer snan, chunri and shringar', 'Offer kumkum-akshat tilak and red flowers', 'Recite Durga Saptashati path or "या देवी सर्वभूतेषु..."', 'Offer bhog (halwa-puri-chana on Ashtami; kanya pujan if possible)', 'Do the aarti "Jai Ambe Gauri"', 'Distribute prasad; bow to all women of the house as Devi-roopa'],
    mantra: 'या देवी सर्वभूतेषु शक्तिरूपेण संस्थिता।\nनमस्तस्यै नमस्तस्यै नमस्तस्यै नमो नमः॥',
    devotionalId: 'jai-ambe-gauri',
    playQuery: 'Durga puja vidhi at home',
  },
  {
    id: 'vishnu',
    deity: 'Lord Vishnu / Satyanarayan',
    deityHi: 'भगवान विष्णु',
    icon: 'chakram',
    color: '#1565C0',
    day: 'Thursday · Ekadashi · Purnima',
    samagri: ['Vishnu/Satyanarayan image', 'Yellow cloth and yellow flowers', 'Tulsi leaves — essential', 'Panchamrit', 'Kela (banana), panjiri/sheera for bhog', 'Haldi, chandan, akshat', 'Kalash, mango leaves, coconut', 'Diya with ghee, dhoop', 'Satyanarayan katha book (for the vrat katha)'],
    offerings: ['Tulsi dal with every bhog — Vishnu accepts nothing without tulsi', 'Yellow sweets, panjiri, banana', 'Chandan and yellow flowers'],
    strictlyAvoid: ['Bhog without tulsi', 'Akshat (rice) offered directly to Vishnu — use til or flowers instead (traditional rule)', 'Onion & garlic in any offering', 'Ekadashi: rice is not eaten or offered'],
    steps: ['Bathe; set the kalash and image facing east on yellow cloth', 'Light diya & dhoop; do achaman and sankalpa', 'Invoke: "ॐ नमो भगवते वासुदेवाय"', 'Offer panchamrit snan, then water; dress with yellow vastra', 'Offer chandan tilak, yellow flowers and TULSI', 'Read/listen to Satyanarayan katha (all 5 chapters) if doing the vrat', 'Offer bhog (sheera/panjiri with tulsi) and banana', 'Do the aarti "Om Jai Jagdish Hare"', 'Distribute prasad to everyone present — never refuse it'],
    mantra: 'ॐ नमो भगवते वासुदेवाय॥\nशान्ताकारं भुजगशयनं पद्मनाभं सुरेशं...',
    devotionalId: 'om-jai-jagdish',
    playQuery: 'Satyanarayan puja vidhi',
  },
  {
    id: 'krishna',
    deity: 'Lord Krishna',
    deityHi: 'श्री कृष्ण',
    icon: 'music',
    color: '#0D47A1',
    day: 'Wednesday · Ashtami · Janmashtami',
    samagri: ['Laddu Gopal / Krishna murti', 'Jhula (swing) for Janmashtami', 'Tulsi leaves', 'Makhan-mishri, dry fruits, panjiri', 'Peacock feather, flute (shringar)', 'Yellow vastra & flowers', 'Panchamrit for abhishek', 'Diya, dhoop, kapoor'],
    offerings: ['Makhan-mishri — Kanha\'s favourite', 'Tulsi with every bhog', 'Panjiri, kheer, seasonal fruit'],
    strictlyAvoid: ['Bhog without tulsi', 'Onion & garlic strictly', 'Stale or tasted food as bhog'],
    steps: ['Bathe Laddu Gopal with panchamrit, then water (abhishek)', 'Dress and adorn — vastra, mukut, peacock feather, flute', 'Apply chandan tilak; place on jhula/asan', 'Light diya & dhoop; offer flowers and tulsi', 'Offer makhan-mishri/panjiri bhog', 'Chant "हरे कृष्ण" mahamantra or read a Gita chapter', 'Do the aarti "Aarti Kunj Bihari Ki"', 'On Janmashtami: midnight birth ceremony with kirtan'],
    mantra: 'हरे कृष्ण हरे कृष्ण, कृष्ण कृष्ण हरे हरे।\nहरे राम हरे राम, राम राम हरे हरे॥',
    devotionalId: 'kunj-bihari',
    playQuery: 'Krishna puja Laddu Gopal seva vidhi',
  },
  {
    id: 'saraswati',
    deity: 'Maa Saraswati',
    deityHi: 'माँ सरस्वती',
    icon: 'book-open-page-variant',
    color: '#B8860B',
    day: 'Thursday · Basant Panchami',
    samagri: ['Saraswati image', 'White/yellow cloth', 'White flowers, palash on Basant Panchami', 'Books, pens, instruments to worship', 'Haldi, chandan, akshat', 'Boondi/kesar sheera for bhog', 'Diya & dhoop'],
    offerings: ['White flowers and white sweets', 'Kesar sheera on Basant Panchami', 'Your books & instruments placed at her feet'],
    strictlyAvoid: ['Keeping torn/disrespected books in the puja', 'Studying materials on the floor near the altar', 'Onion & garlic in bhog'],
    steps: ['Clean the study/altar space; set the image on white/yellow cloth', 'Place your books, pens or instruments before Maa', 'Light diya & dhoop; do sankalpa for vidya', 'Offer chandan tilak, akshat and white/yellow flowers', 'Chant the Saraswati Vandana', 'Offer bhog; on Basant Panchami wear yellow', 'Do the Saraswati aarti', 'Children traditionally write their first letters today (Vidyarambha)'],
    mantra: 'या कुन्देन्दुतुषारहारधवला या शुभ्रवस्त्रावृता...\nसा मां पातु सरस्वती भगवती निःशेषजाड्यापहा॥',
    devotionalId: 'saraswati-vandana',
    playQuery: 'Saraswati puja vidhi Basant Panchami',
  },
  {
    id: 'shani',
    deity: 'Shani Dev',
    deityHi: 'शनि देव',
    icon: 'orbit',
    color: '#455A64',
    day: 'Saturday',
    samagri: ['Shani image or shila (often worshipped at the temple, not home altar)', 'Sarson (mustard) oil', 'Black til (sesame)', 'Black cloth / blue flowers', 'Iron diya if available', 'Urad dal khichdi for bhog/daan'],
    offerings: ['Mustard oil (poured over the shila at a Shani temple)', 'Black til, black urad', 'Shani daan: oil, iron, black cloth to the needy'],
    strictlyAvoid: ['Common tradition: women & the general devotee do not touch the Shani murti — offer from a respectful distance', 'Facing Shani\'s eyes directly at temples (drishti tradition)', 'Alcohol/non-veg on Saturday for the vrati'],
    steps: ['Saturday morning, bathe after applying a little til oil', 'Visit a Shani temple if possible; else worship facing west at home', 'Offer mustard oil, black til and blue/black items', 'Chant "ॐ शं शनैश्चराय नमः" (a mala if under sade-sati)', 'Recite Shani Chalisa or Dashrath-krit Shani Stotra', 'Light a til-oil diya under a peepal tree in the evening', 'Do daan: khichdi/oil/iron to the needy — Shani values seva over show', 'Also honour Hanuman ji — his devotees are shielded from Shani\'s hard gaze'],
    mantra: 'ॐ नीलांजनसमाभासं रविपुत्रं यमाग्रजम्।\nछायामार्तण्डसम्भूतं तं नमामि शनैश्चरम्॥',
    devotionalId: 'hanuman-chalisa',
    playQuery: 'Shani dev puja vidhi Saturday',
  },
  {
    id: 'surya',
    deity: 'Surya Dev',
    deityHi: 'सूर्य देव',
    icon: 'white-balance-sunny',
    color: '#F59E0B',
    day: 'Sunday · Chhath · Makar Sankranti',
    samagri: ['Copper lota (tamra kalash)', 'Clean water with roli & red flowers', 'Red chandan, akshat', 'Gur (jaggery) or wheat items for bhog/daan', 'A clear view of the rising sun'],
    offerings: ['Arghya — water offered to the rising sun', 'Red flowers in the arghya water', 'Gur-wheat daan on Sundays'],
    strictlyAvoid: ['Offering arghya after sunrise is well past (best within the first hour)', 'Looking directly at the bright sun — gaze at the reflection/stream of water instead', 'Salt in Sunday vrat food (traditional)'],
    steps: ['Wake before sunrise; bathe', 'Fill the copper lota with water; add roli, akshat, red flowers', 'Face the rising sun, water falling in a steady stream — "ॐ सूर्याय नमः"', 'Offer arghya 3 times, rotating gently', 'Chant the Gayatri Mantra or Aditya Hridayam if you know it', 'Do namaskar (or Surya Namaskar as sadhana)', 'On Sundays: gur/wheat daan to the needy'],
    mantra: 'ॐ भूर्भुवः स्वः। तत्सवितुर्वरेण्यं।\nभर्गो देवस्य धीमहि। धियो यो नः प्रचोदयात्॥',
    devotionalId: 'gayatri',
    playQuery: 'Surya arghya vidhi morning',
  },
];
