// Sadhak — Kundli PDF report. Builds a clean printable HTML from the computed
// chart and turns it into a real PDF via expo-print, then opens the share sheet.
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import type { Kundli, BirthInput } from './jyotish';

const esc = (s: any) => String(s ?? '').replace(/[&<>]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[c] as string));

function buildHtml(k: Kundli, birth: BirthInput | null, name?: string): string {
  const b = k.basics;
  const planetRows = k.planets.map((p) => `
    <tr><td><b>${esc(p.name)}</b>${p.retro ? ' <span class="r">R</span>' : ''}</td>
    <td>${esc(p.sign)} ${p.degree.toFixed(2)}&deg;</td><td>H${p.house}</td>
    <td>${esc(p.nakshatra)} (${p.pada})</td><td>${esc(p.dignity && p.dignity !== '—' ? p.dignity : '')}</td></tr>`).join('');
  const dashaRows = (k.dasha?.maha || []).map((m) => `<tr><td>${esc(m.lord)}</td><td>${esc(m.start)} &ndash; ${esc(m.end)}</td></tr>`).join('');
  const yogaRows = (k.yogas || []).map((y) => `<li><b>${esc(y.name)}</b> — ${esc(y.desc)}</li>`).join('') || '<li>No major classical yogas from the curated set.</li>';
  const d = k.doshas;
  const doshaRows = d ? `
    <li>Mangal (Kuja) Dosha: <b>${d.mangal.present ? `Present (Mars in house ${d.mangal.house})` : 'Not present'}</b></li>
    <li>Kaal Sarp Dosha: <b>${d.kaalSarp.present ? 'Present' : 'Not present'}</b></li>
    <li>Sade Sati: <b>${d.sadeSati.present ? `${d.sadeSati.phase} phase (Saturn in ${d.sadeSati.saturnSign})` : 'Not active now'}</b></li>` : '';

  return `<!doctype html><html><head><meta charset="utf-8"/>
  <style>
    @page { margin: 32px; }
    * { box-sizing: border-box; }
    body { font-family: -apple-system, 'Segoe UI', Roboto, sans-serif; color: #1a1a1a; font-size: 12px; }
    .hd { text-align:center; border-bottom: 2px solid #C2410C; padding-bottom: 12px; margin-bottom: 16px; }
    .hd h1 { margin: 0; color: #C2410C; font-size: 22px; letter-spacing: 1px; }
    .hd p { margin: 3px 0; color: #555; }
    h2 { color:#C2410C; font-size: 13px; text-transform: uppercase; letter-spacing: 1px; border-bottom:1px solid #eee; padding-bottom:4px; margin: 18px 0 8px; }
    table { width:100%; border-collapse: collapse; }
    td, th { padding: 5px 7px; border-bottom: 1px solid #eee; text-align:left; }
    .grid { display:flex; flex-wrap:wrap; }
    .grid div { width:50%; padding: 3px 0; }
    .r { color:#C2410C; font-weight:bold; }
    ul { margin: 4px 0; padding-left: 18px; }
    li { margin: 3px 0; }
    .foot { margin-top: 22px; text-align:center; color:#999; font-size: 10px; border-top:1px solid #eee; padding-top:8px; }
  </style></head><body>
  <div class="hd"><h1>SADHAK &middot; KUNDLI</h1>
    <p><b>${esc(name || 'Devotee')}</b></p>
    <p>${birth ? `Born ${esc(birth.date)}${birth.hasTime ? ' at ' + esc(birth.time) : ''} &middot; ${esc(birth.place)}` : ''}</p>
  </div>
  <h2>Core</h2>
  <div class="grid">
    <div>Lagna (Ascendant): <b>${esc(b.lagna)}</b></div>
    <div>Rashi (Moon): <b>${esc(b.rashi)}</b> &middot; lord ${esc(b.rashiLord)}</div>
    <div>Nakshatra: <b>${esc(b.nakshatra)}</b> pada ${b.pada}</div>
    <div>Nakshatra lord: <b>${esc(b.nakLord)}</b></div>
    <div>Gana: <b>${esc(b.gana)}</b></div>
    <div>Nadi: <b>${esc(b.nadi)}</b></div>
    <div>Yoni: <b>${esc(b.yoni)}</b></div>
    <div>Ishta Devata group: <b>${esc(b.deity)}</b></div>
  </div>
  <h2>Graha Positions (D1)</h2>
  <table><tr><th>Planet</th><th>Sign</th><th>House</th><th>Nakshatra</th><th>Dignity</th></tr>${planetRows}</table>
  ${dashaRows ? `<h2>Vimshottari Mahadasha</h2><table><tr><th>Lord</th><th>Period</th></tr>${dashaRows}</table>` : ''}
  <h2>Yogas</h2><ul>${yogaRows}</ul>
  ${doshaRows ? `<h2>Dosha Check</h2><ul>${doshaRows}</ul>` : ''}
  <div class="foot">Calculated with Swiss Ephemeris &middot; Lahiri ayanamsa &middot; whole-sign houses.<br/>Generated by Sadhak &middot; sadhak-app.vercel.app</div>
  </body></html>`;
}

/** Build the PDF and open the share sheet. */
export async function exportKundliPdf(k: Kundli, birth: BirthInput | null, name?: string): Promise<void> {
  const html = buildHtml(k, birth, name);
  const { uri } = await Print.printToFileAsync({ html, base64: false });
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: 'Your Sadhak Kundli', UTI: 'com.adobe.pdf' });
  }
}
